apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- monitoring
- storage
- grpc-ingress.yaml 
- http-ingress.yaml
- namespace.yaml
- nginx-config.yaml
- nginx-ingress-class.yaml