apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- grpc-ingress.yaml 
- http-ingress.yaml
- namespace.yaml
- nginx-config.yaml
- nginx-ingress-class.yaml

secretGenerator:
- name: tls-secret
  files:
  - tls.crt
  - tls.key