name: 'Prepare kustomize'
description: Prepare necessary infra for kustomize'
inputs:
  tlsCertificate:
    description: 'Tls certificate content'
    required: true
  tlsKey:
    description: 'Tls key'
    required: true
  firebaseSdkFileContent:
    description: 'Firebase SDK file content'
    required: true
  dockerConfigFileContent:
    description: 'Docker config file content'
    required: true
env:
  TlsCertificateFile: "tls.crt"
  TlsKeyFile: "tls.key"
  FirebaseSDKfile: "adminsdk.json"
  DockerconfigFile: ".dockerconfigjson"
runs:
  using: "composite"
  steps:
  - name: Certificates create
    run: |
      echo -n '${{ inputs.tlsCertificate }}' > ./k8s/base/infra/${{ env.TlsCertificateFile }}
      echo -n '${{ inputs.tlsKey }}' > ./k8s/base/infra/${{ env.TlsKeyFile }}
    shell: bash
  - name: Create firebase secret
    run: |
      echo -n '${{inputs.firebaseSdkFileContent}}' > ./k8s/base/infra/${{env.FirebaseSDKfile}}
    shell: bash
  - name: Create ghcr secret
    run: |
      echo -n '${{inputs.dockerConfigFileContent}}' > ./k8s/base/infra/${{env.DockerconfigFile}}
    shell: bash