name: 'Deploy  resources'
description: 'Deploys resources from provided kustomization.yaml file to chosen environment'
inputs:
  environment:
    description: 'Environment to be deployed'
    required: true
  resourceLabel:
    description: 'Label of the resource to be deployed'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
  - name: SetUp Kustomize with label
    if: inputs.resourcesLabels == ''
    run: kubectl apply -k ./k8s/overlays/${{ inputs.environment }}
    shell: bash
  - name: SetUp Kustomize without label
    if: inputs.resourcesLabels != ''
    run: kubectl apply -k ./k8s/overlays/${{ inputs.environment }} -l resource=${{inputs.resourceLabel}}
    shell: bash