name: 'Deploy  resources'
description: 'Deploys resources from provided kustomization.yaml file to chosen environment'
inputs:
  environment:
    description: 'Environment to be deployed'
    required: true
  resourcesLabels:
    description: 'Label(s) of the resource(s) to be deployed'
    type: array
    required: false
runs:
  using: "composite"
  steps:
  - name: SetUp Kustomize with label
    if: inputs.resourcesLabels == '[]'
    run: kubectl apply -k ./k8s/overlays/${{ inputs.environment }}
    shell: bash
  - name: SetUp Kustomize without label
    if: inputs.resourcesLabels != '[]'
    run: kubectl apply -k ./k8s/overlays/${{ inputs.environment }} -l 'resource in (${{ join( inputs.resourcesLabels, ', ') }})'
    shell: bash