name: 'Deploy  resources'
description: 'Deploys resources from provided kustomization.yaml file to chosen environment'
inputs:
  environment:
    description: 'Environment to be deployed'
    required: true
  resourceTypeLabel:
    description: 'Label of the resource type to be deployed'
    required: false
  resourceLabel:
    description: 'Label of the resource to be deployed'
    required: false
runs:
  using: "composite"
  steps:
  - name: Create base command
    run: command='kubectl apply -k ./k8s/overlays/${{ inputs.environment }}'
    shell: bash
  - name: Add resource type label
    if: inputs.resourceLabel != ''
    run: command+='-l resourceType=${{inputs.resourceTypeLabel}}'
    shell: bash
  - name: Add resource label
    if: inputs.resourceLabel != ''
    run: command+='-l resource=${{inputs.resourceLabel}}'
    shell: bash
  - name: Run command
    run: eval $command
    shell: bash