name: 'Deploy  resources'
description: 'Deploys resources from provided kustomization.yaml file to chosen environment'
inputs:
  environment:
    description: 'Environment to be deployed'
    required: true
  resourcePath:
    description: 'Relative path to kustomization.yaml file from environment overlay'
    required: true
runs:
  using: "composite"
  steps:
  - name: SetUp Kustomize
    run: kubectl apply -k ./k8s/overlays/${{ inputs.environment }}/${{ inputs.resourcePath }}}