name: "Publish all nugets"
description: "Publish all nugets"
inputs:
  folder:
    description: "Name of a folder to download nugets into"
    required: true
  name:
    description: "Project name"
    required: true
  nuget-source-name:
    description: "Name of a nuget source to upload"
    required: true
    default: "github"
  token:
    description: "Token to publish nugets"
    required: true
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - name: Download nugets
      id: download
      uses: actions/download-artifact@v3
      with:
        name: nugets_${{ inputs.name }}
        path: ${{ inputs.folder }}/temp
    - name: Publish downloaded nugets
      run: dotnet nuget push "${{ steps.download.outputs.download-path }}/**/*.nupkg" --api-key ${{ inputs.token }} --source ${{ inputs.nuget-source-name }}
      shell: bash