name: "Upload test results"
description: "Upload all test results to Codecov"
inputs:
  name:
    description: "Name of the project that will be passed as flag"
    required: true
  codecov-token:
    description: "Token to upload test results"
    required: true
runs:
  using: "composite"
  steps:
    - name: Download test results
      id: download
      uses: actions/download-artifact@v3
      with:
        name: test-results
        path: ./.temp/coverage
    - name: Upload unit tests to codecov
      uses: codecov/codecov-action@v3
      with: 
        token: ${{ inputs.codecov-token }}
        directory: ./.temp/coverage/units
        flags: |
          ${{ inputs.name }}
          units
        fail_ci_if_error: true
    - name: Upload integration tests to codecov
      uses: codecov/codecov-action@v3
      with: 
        token: ${{ inputs.codecov-token }}
        directory: ./.temp/coverage/integrations
        flags: |
          ${{ inputs.name }}
          integrations
        fail_ci_if_error: true