name: "Upload test results"
description: "Upload all test results to Codecov with project name as carryforward flag"
inputs:
  folder:
    description: "Name of a folder to download test results into"
    required: true
  name:
    description: "Name of the project that will be passed as flag"
    required: true
  codecov-token:
    description: "Token to upload test results"
    required: true
runs:
  using: "composite"
  steps:
    - name: Download test results
      id: download
      uses: actions/download-artifact@v3
      with:
        name: test-results
        path: ${{ inputs.folder }}/temp/coverage
    - name: Upload unit tests to codecov
      uses: codecov/codecov-action@v3
      with: 
        token: ${{ inputs.codecov-token }}
        directory: ${{ steps.download.outputs.download-path }}
        flags: ${{ inputs.name }}
        fail_ci_if_error: true