apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: crescore-cert
  namespace: crescore
spec:
  secretName: crescore-cert-secret
  dnsNames:
  - "*.uniscore.ru"
  - "*.grpc.uniscore.ru"
  issuerRef:
    name: letsencrypt-staging
      # name: letsencrypt-prod
    kind: ClusterIssuer
