apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert
  namespace: uniscore
spec:
  secretName: cert-secret
  dnsNames:
  - "*.uniscore.ru"
  - "*.grpc.uniscore.ru"
  issuerRef:
    name: letsencrypt-staging
      # name: letsencrypt-prod
    kind: ClusterIssuer
