apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graf-data-dir-pvc
  namespace: monitoring
spec:
  storageClassName: "longhorn-local"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
