apiVersion: apps/v1
kind: Deployment
metadata:
  name: placeholder
  namespace: uniscore
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: placeholder
  template:
    metadata:
      namespace: uniscore
      labels:
        app: placeholder
    spec:
      imagePullSecrets:
      - name: dockerconfigjson-github-com
      containers:
      - name: placeholder-container
        imagePullPolicy: Always
        image: ghcr.io/kamushekdev/uniscore-placeholder:latest
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 5
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          timeoutSeconds: 2
          failureThreshold: 3
          successThreshold: 1
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "200m"