name: 'Build all .NET solutions'
description: 'Build all .NET solutions under specific folder'
inputs:
  folder:
    description: 'Root folder for scanning for solutions'
    required: true
  version:
    description: 'Version'
    required: true
runs:
  using: "composite"
  steps:
    - name: Build all solutions
      run: |
        solutions=$(find ${{ inputs.folder }} -type f -name "*.sln") \
        && for solution in $solutions; do echo $solution; dotnet publish -c Release /p:Version=${{ inputs.version }} $solution; done
      shell: bash
    - name: Locate all nuget files
      id: nugets
      run: |
        nugets=$(find ${{ inputs.folder }} -type f -name "*.nupkg") \
        && echo "::set-output name=nuget-files::$(echo $nugets)"
      shell: bash
    - name: Upload all nugets to artifacts
      uses: actions/upload-artifact@v3
      with:
        name: nugets
        path: ${{ steps.nugets.outputs.nuget-files }}
