apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: uniscore
  annotations:
    cloud.google.com/app-protocols: '{"grpc":"HTTP2", "http": "HTTP"}'
    service.alpha.kubernetes.io/app-protocols: '{"grpc":"HTTP2", "http": "HTTP"}'
spec:
  selector:
    app: auth
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: grpc
    port: 82
    targetPort: 82
    protocol: TCP
  type: NodePort
