apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: uniscore
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      namespace: uniscore
      labels:
        app: auth
    spec:
      imagePullSecrets:
      - name: dockerconfigjson-github-com
      containers:
      - name: auth-container
        image: ghcr.io/kamushekdev/uniscore-auth:{VERSION}
        volumeMounts:
          - name: firebase-admin-sdk
            mountPath: /app/secrets
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 5
          httpGet:
            path: /live
            port: 80
            scheme: HTTP
          timeoutSeconds: 2
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 10
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
          timeoutSeconds: 2
          failureThreshold: 3
          successThreshold: 1
        resources:
          requests:
            memory: "64Mi"
            cpu: "150m"
          limits:
            memory: "128Mi"
            cpu: "300m"
      volumes:
        - name: firebase-admin-sdk
          secret:
            secretName: firebase-admin-sdk-json
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: uniscore
  annotations:
    cloud.google.com/app-protocols: '{"grpc":"HTTP2", "http": "HTTP"}'
    service.alpha.kubernetes.io/app-protocols: '{"grpc":"HTTP2", "http": "HTTP"}'
spec:
  selector:
    app: auth
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: grpc
    port: 82
    targetPort: 82
    protocol: TCP
  type: NodePort
