name: "Test all .NET solutions"
description: "Test all .NET solutions under specific folder"
inputs:
  folder:
    description: "Root folder for scanning for solutions"
    required: true
runs:
  using: "composite"
  steps:
    # todo: Separate tests to unit tests + integration tests
    # --filter parameter
    - name: Run all unit tests
      run: |
        solutions=$(find ${{ inputs.folder }} -type f -name "*.sln") \
        && for solution in $solutions; do echo $solution; dotnet test $solution --collect:"XPlat Code Coverage" -r ./coverage/integrations --filter "FullyQualifiedName!~IntegrationTests"; done
      shell: bash
    - name: Run all integration tests
      run: |
        solutions=$(find ${{ inputs.folder }} -type f -name "*.sln") \
        && for solution in $solutions; do echo $solution; dotnet test $solution --collect:"XPlat Code Coverage" -r ./coverage/units --filter "FullyQualifiedName~IntegrationTests"; done
      shell: bash
    - name: Upload coverage results to artifacts
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: "./coverage"
        retention-days: 30