name: Kubernetes cluster init
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to be deployed on'
        required: true
        type: choice
        options:
        - production
        - staging
jobs:
  init-cluster:
    runs-on: ubuntu-latest
    env:
      ConfigFileDir: "configs"
      OvpnConfigFile: "config.ovpn"
      KubeCtlConfigFile: "kubeConfig"
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: OpenVpn setup
        uses: ./.github/actions/deploy/openVpn-setup-connect
        with: 
          openVpnConfig: ${{ secrets.VPN_CONFIG }}
          openVpnUserName: ${{ secrets.VPN_USERNAME }}
          openVpnUserPassword: ${{ secrets.VPN_PASSWORD }}
      - name: Kubectl setup
        uses: Azure/setup-kubectl@v3
      - name: Setup kubectl config
        uses: ./.github/actions/deploy/kubectl-setup
        with: 
          kubeConfig: ${{ secrets.KUBE_CONFIG }}
      - name: Install ingress-nginx
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.7.1/deploy/static/provider/baremetal/deploy.yaml
        shell: bash
      - name: Install longhorn
        run: |
          kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml
        shell: bash