name: dotnet - Uniscore.Shared
on:
  push:
    paths:
      - '.github/**'
      - 'dotnet/uniscore-shared/**'
jobs:
  Init:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}
    - name: Checkout
      uses: actions/checkout@v1
    - name: Generate version
      id: version
      uses: .github/actions/generate-version/
      with: 
        branch: ${{github.ref_name}}
        build-number: ${{github.run_number}}
        run-attempt: ${{github.run_attempt}}
