name: dotnet - Unicsore.Auth - Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to be deployed'
        required: true
        type: choice
        options:
        - production
        - staging
jobs:
  deploy-prep:
    uses: ./.github/workflows/dotnet-uniscore-auth.yaml
    secrets: inherit
  
  publish:
    needs: deploy-prep
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      ConfigFileDir: "configs"
      OvpnConfigFile: "config.ovpn"
      KubeCtlConfigFile: "kubeConfig"
    steps:
      - name: OpenVPN-ConfigFile-Download
        run: |
          mkdir ${{ env.OvpnConfigFileDir }}
          echo "${{ secrets.VPN_CONFIG }}" > ${{ env.ConfigFileDir }}/${{ env.OvpnConfigFile }}
      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved
      - name: OpenVPN-Connect
        uses: kota65535/github-openvpn-connect-action@v2.0.2
        with:
          config_file: ${{ env.ConfigFileDir }}/${{ env.OvpnConfigFile }}
          username: ${{ secrets.VPN_USERNAME }}
          password: ${{ secrets.VPN_PASSWORD }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v3
      - name: Setup kubectl config
        run: |
          mkdir ${{ env.KubeCtlConfigFileDir }}
          echo "${{ secrets.KUBE_CONFIG }}" >  ${{ env.ConfigFileDir }}/${{ env.KubeCtlConfigFile }}
          echo "KUBECONFIG=`pwd`/${{ env.ConfigFileDir }}/${{ env.KubeCtlConfigFile }}" >> $GITHUB_ENV
      - name: SetUp Kustomize
        run: |
          cd ./k8s/overlays/${{ inputs.environment }}/services/${{ needs.deploy-prep.outputs.project_name }}
          kubectl apply -k ./
      - name: Restart service
        run: |
          kubectl rollout restart -f ./k8s/overlays/${{ inputs.environment }}/services/${{ needs.deploy-prep.outputs.project_name }}
    
