name: dotnet - Uniscore.Shared
on:
  push:
    paths:
      - ".github/**"
      - "dotnet/uniscore-shared/**"
env:
  folder: "./dotnet/uniscore-shared"
  name: "uniscore-shared"
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate version
        id: version
        uses: ./.github/actions/generate-version

  build:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup dotnet
        uses: xt0rted/setup-dotnet@v1
        with:
          dotnet-version: |
            6.0.303
      - name: Add source
        uses: ./.github/actions/add-github-source
      - name: Cache nuget
        uses: actions/cache@v1
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ env.folder }}-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            nuget-${{ runner.os }}-${{ env.folder }}-
            nuget-${{ runner.os }}-
      - name: Build
        uses: ./.github/actions/build-dotnet
        with: 
          folder: ${{ env.folder }}
          version: ${{ needs.init.outputs.version }}

  tests:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup dotnet
        uses: xt0rted/setup-dotnet@v1
        with:
          dotnet-version: |
            6.0.303
      - name: Tests
        uses: ./.github/actions/test-dotnet
        with:
          folder: ${{ env.folder }}        

  publish-nugets:
    runs-on: ubuntu-latest
    needs: [build, tests]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add source
        uses: ./.github/actions/add-github-source
      - name: Publish nugets
        uses: ./.github/actions/publish-nugets

  upload-test-results:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Upload tests
        uses: ./.github/actions/upload-to-codecov
        with: 
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
          name: ${{ inputs.name }}  