name: dotnet - Uniscore.Shared
on:
  push:
    paths:
      - ".github/**"
      - "dotnet/uniscore-shared/**"
jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v1
      - name: Generate version
        id: version
        uses: ./.github/actions/generate-version
  build:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Test
        run: echo ${{ needs.init.outputs.version }}
      - name: Build
        uses: ./.github/actions/build-dotnet
        with: 
          folder: './dotnet/uniscore-shared'
          version: ${{ needs.init.outputs.version }}
