name: dotnet - Unicsore.Auth - Publish
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to be deployed'
        required: true
        type: choice
        options:
        - Production
        - Staging
jobs:
  uses-dotnet-uniscore-auth:
    uses: ./.github/workflows/dotnet-uniscore-auth.yaml
  
  publish:
    needs: uses-dotnet-uniscore-auth
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      OvpnConfigFileDir: "OpenVpn"
      OvpnConfigFile: "config.ovpn"
    steps:
      - name: OpenVPN-ConfigFile-Download
        run: |
          mkdir ${{ env.OvpnConfigFileDir }}
          echo "${{ secrets.VPN_CONFIG }}" > ${{ env.OvpnConfigFileDir }}/${{ env.OvpnConfigFile }}
      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved
      - name: OpenVPN-Connect
        uses: kota65535/github-openvpn-connect-action@v2.0.2
        with:
          config_file: ${{ env.OvpnConfigFileDir }}/${{ env.OvpnConfigFile }}
          username: ${{ secrets.VPN_USERNAME }}
          password: ${{ secrets.VPN_PASSWORD }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v3
      - name: Replace kubectl config
        run: |
          cd $HOME/.kube
          cat ${{ secrets.KUBE_CONFIG }} > config
      - name: SetUp-Kustomize
        run: |
          cd ./k8s/overlays/${{ inputs.environment }}/services/${{ env.folder }}
          dir

    
