name: dotnet - Unicsore.Auth - Publish
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to be deployed'
        required: true
        type: choice
        options:
        - Production
        - Staging
jobs:
  #uses-dotnet-uniscore-auth:
    #uses: ./.github/workflows/dotnet-uniscore-auth.yaml
  
  connect-vpn:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      OvpnCofigFile: "config.ovpn"
    steps:
      - name: OpenVPN-ConfigFile-Download
        run: echo "${{ secrets.VPN_CONFIG }}" > ${{ env.OvpnCofigFile }}
      - name: OpenVPN-Connect
        uses: kota65535/github-openvpn-connect-action@v2.0.2
        with:
          # how to choose environment of variables? 
          config_file: ${{ env.OvpnCofigFile }}
          username: ${{ secrets.VPN_USERNAME }}
          password: ${{ secrets.VPN_PASSWORD }}
      - name: PingPcInLocalHost
        run: ping 192.168.1.10 
