name: Infra - Deploy
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to be deployed on'
        required: true
        type: choice
        options:
        - production
        - staging
jobs:
  deploy-infa:
    runs-on: ubuntu-latest
    env:
      ConfigFileDir: "configs"
      OvpnConfigFile: "config.ovpn"
      KubeCtlConfigFile: "kubeConfig"
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: OpenVpn setup
        uses: ./.github/actions/deploy/openVpn-setup-connect
        with: 
          openVpnConfig: ${{ secrets.VPN_CONFIG }}
          openVpnUserName: ${{ secrets.VPN_USERNAME }}
          openVpnUserPassword: ${{ secrets.VPN_PASSWORD }}
      - name: Kubectl setup
        uses: Azure/setup-kubectl@v3
      - name: Setup kubectl config
        uses: ./.github/actions/deploy/kubectl-setup
        with: 
          kubeConfig: ${{ secrets.KUBE_CONFIG }}
      - name: Prepare kustomize
        uses: ./.github/actions/deploy/prepare-kustomize
        with:
          tlsCertificate: ${{ secrets.KUBE_TLS_CRT }}
          tlsKey: ${{ secrets.KUBE_TLS_KEY }}
          firebaseSdkFileContent: ${{secrets.FIREBASE_ADMIN_SDK_JSON}}
          dockerConfigFileContent: ${{secrets.DOCKER_CONFIG_JSON}}
      - name: Deploy infra
        uses: ./.github/actions/deploy/deploy-resources
        with: 
          environment: ${{ inputs.environment }}

  restart-services:
    needs: deploy-infa
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    strategy:
      matrix:
        service: ['uniscore-auth', 'uniscore-scores', 'uniscore-users', 'uniscore-placeholder']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: OpenVpn setup
        uses: ./.github/actions/deploy/openVpn-setup-connect
        with: 
          openVpnConfig: ${{ secrets.VPN_CONFIG }}
          openVpnUserName: ${{ secrets.VPN_USERNAME }}
          openVpnUserPassword: ${{ secrets.VPN_PASSWORD }}
      - name: Kubectl setup
        uses: Azure/setup-kubectl@v3
      - name: Setup kubectl config
        uses: ./.github/actions/deploy/kubectl-setup
        with: 
          kubeConfig: ${{ secrets.KUBE_CONFIG }}
      - name: Restart service
        uses: ./.github/actions/deploy/service-restart
        with: 
          service: ${{ matrix.service }}