name: Infra - Deploy
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to be deployed on'
        required: true
        type: choice
        options:
        - staging
        - production
jobs:
  rebuild-dotnet-services:
    strategy:
      matrix:
        service: ['uniscore-auth', 'uniscore-scores', 'uniscore-users']
    uses: ./.github/workflows/dotnet.yaml
    with:
      project_name: ${{ matrix.service }}
    secrets: inherit

  rebuild-uniscore-placeholder:
    uses: ./.github/workflows/react-uniscore-placeholder.yaml
    secrets: inherit

  deploy-infa:
    needs: [rebuild-dotnet-services, rebuild-uniscore-placeholder]
    runs-on: ubuntu-latest
    env:
      ConfigFileDir: "configs"
      OvpnConfigFile: "config.ovpn"
      KubeCtlConfigFile: "kubeConfig"
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: OpenVpn setup
        uses: ./.github/actions/deploy/openVpn-setup-connect
        with: 
          openVpnConfig: ${{ secrets.VPN_CONFIG }}
          openVpnUserName: ${{ secrets.VPN_USERNAME }}
          openVpnUserPassword: ${{ secrets.VPN_PASSWORD }}
      - name: Kubectl setup
        uses: Azure/setup-kubectl@v3
      - name: Setup kubectl config
        uses: ./.github/actions/deploy/kubectl-setup
        with: 
          kubeConfig: ${{ secrets.KUBE_CONFIG }}
      - name: Prepare kustomize
        uses: ./.github/actions/deploy/prepare-kustomize
        with:
          tlsCertificate: ${{ secrets.KUBE_TLS_CRT }}
          tlsKey: ${{ secrets.KUBE_TLS_KEY }}
          firebaseSdkFileContent: ${{ secrets.FIREBASE_ADMIN_SDK_JSON }}
          dockerConfigFileContent: ${{ secrets.DOCKER_CONFIG_JSON }}
      - name: Deploy infra
        uses: ./.github/actions/deploy/deploy-resources
        with: 
          environment: ${{ inputs.environment }}

  restart-services:
    needs: deploy-infa
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    strategy:
      matrix:
        service: ['uniscore-auth', 'uniscore-scores', 'uniscore-users', 'uniscore-placeholder']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: OpenVpn setup
        uses: ./.github/actions/deploy/openVpn-setup-connect
        with: 
          openVpnConfig: ${{ secrets.VPN_CONFIG }}
          openVpnUserName: ${{ secrets.VPN_USERNAME }}
          openVpnUserPassword: ${{ secrets.VPN_PASSWORD }}
      - name: Kubectl setup
        uses: Azure/setup-kubectl@v3
      - name: Setup kubectl config
        uses: ./.github/actions/deploy/kubectl-setup
        with: 
          kubeConfig: ${{ secrets.KUBE_CONFIG }}
      - name: Restart service
        uses: ./.github/actions/deploy/service-restart
        with: 
          service: ${{ matrix.service }}

  deduplicate-deployments:
    if: ${{ always() }}
    needs: restart-services
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Successfull deployment
        if: ${{ needs.restart-services.result == 'success' }}
        uses: ./.github/actions/github-deployments-deduplication
        with:
          environment: ${{ inputs.environment }}
          resultState: 'success'
      - name: Failed deployment 
        if: ${{ needs.restart-services.result != 'success' }}
        uses: ./.github/actions/github-deployments-deduplication
        with:
          environment: ${{ inputs.environment }}
          resultState: 'failure'