name: Scores
on:
  push:
    branches:    
      - 'main'
      - 'test'
jobs:
  Build-PublishNugets:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install .NET SDK
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: '6.0.x'
    - name: Generate version
      run: export BUILD_VERSION=$(date +'%Y.%m.%d').${{github.run_number}}
    - name: Add github packages source
      run: "dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github \"https://nuget.pkg.github.com/OWNER/index.json\""
    - name: Build all solutions
      run: ./.github/scripts/build-all-projects.sh
      shell: bash
    - name: Publish nugets
      run: ./.github/scripts/publish-all-nugets.sh
      shell: bash
