name: Publish nugets
on:
  push:
    branches:    
      - 'main'
jobs:
  Generate-Publish-Nugets:
    runs-on: ubuntu-latest
    steps:
    - run: "dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github \"https://nuget.pkg.github.com/OWNER/index.json\""