name: react - uniscore-placeholder
on:
  push:
    paths:
      - ".github/**"
      - "react/placeholder/**"
env:
  folder: "./react/placeholder"
  name: "uniscore-placeholder"
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

  registry: "ghcr.io"


jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate version
        id: version
        uses: ./.github/actions/generate-version

  prepare-service-builder:
    runs-on: ubuntu-latest
    needs: init
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create tag
        id: tag
        uses: ./.github/actions/create-tag
        with:
          version: ${{ needs.init.outputs.version}}
          name: ${{ env.name }}
          repository-owner-name: ${{ github.repository_owner }}
          registry: ${{ env.registry }}

  build-service-image:
    runs-on: ubuntu-latest
    needs: prepare-service-builder
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.registry }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.folder }}
          push: true
          tags: ${{ needs.prepare-service-builder.outputs.tag }}