name: dotnet - Uniscore.Shared
on:
  workflow_dispatch:

  push:
    # branches:
    #   - 'master'
    paths:
      - ".github/**"
      - "!.github/workflows/**"
      - ".github/workflows/uniscore-shared.yaml"
      - ".github/workflows/dotnet.yaml"
      - "dotnet/uniscore-shared/**"

jobs:
  build-project:
    uses: ./.github/workflows/dotnet.yaml
    with:
      project_name: "uniscore-shared"
    secrets: inherit
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true