name: dotnet - Uniscore.Event.Twitch
on:
  workflow_call:

  push:
    # branches:
    #   - 'master'
    paths:
      - ".github/**"
      - "!.github/workflows/**"
      - ".github/workflows/uniscore-events-twitch.yaml"
      - ".github/workflows/dotnet.yaml"
      - "dotnet/uniscore-events-twitch/**"

jobs:
  build-project:
    uses: ./.github/workflows/dotnet.yaml
    with:
      project_name: "uniscore-events-twitch"
    secrets: inherit